services:
  - name: client
    type: web
    env: node
    plan: free
    buildCommand: |
      cd client && npm install && npm run build
    startCommand: serve -s client/build
    envVars:
      - key: PORT
        value: 3000
    autoDeploy: true

  - name: server
    type: web
    env: node
    plan: free
    buildCommand: |
      cd server && npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 8008
    autoDeploy: true
